name: Deployment

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify

      - name: Copy file via scp
        uses: appleboy/scp-action@master
        env:
          HOST: "46.101.12.134"
          USERNAME: "root"
          PORT: "22"
          PASSWORD: "7lnWu#D3Y3m91XyB"
        with:
          source: "./target/user-service-0.0.1-SNAPSHOT.jar"
          target: "/tmp/user"

      - name: Restart user service
        uses: appleboy/ssh-action@master
        with:
          HOST: "46.101.12.134"
          USERNAME: "root"
          PORT: "22"
          PASSWORD: "7lnWu#D3Y3m91XyB"
          script: |
            mv /tmp/user/target/user-service-0.0.1-SNAPSHOT.jar  /opt/user-service/user-service.jar
            supervisorctl restart userservice


